server:
  port: ${PORT:8080}
  servlet:
    context-path: /dscommerceq

spring:
  application:
    name: dscommerceq
    version: 1.0.0
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_IP}:${DATABASE_PORT}/dscommerceq
    username: ${DATABASE_USERNAME}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    baselineOnMigrate: true
    check-location: true
    schemas: public
    enabled: true


